---
title: "Presence GLMERs"
output: html_notebook
---

Set Up
```{r}
# import packages
library('glue')
library('lme4')
library('tidyverse')
```

```{r}
# flag to save and print tables
save_tables = FALSE
print_tables = FALSE

# set directories
setwd("..")
base_dir = getwd()
data_dir = glue('{base_dir}/Source_Data/')
tbl_dir = glue('{base_dir}/tables/')
```

Table S8
```{r}
# load data
all_data = read_csv(glue('{data_dir}tbl_s8.csv'), show_col_types = FALSE)

# define variables 
ROIs = c('VWFA1','VWFA2','FFA1','FFA2')
GROUPS = c('intervention','dys_control','typ_control')

# loop through ROis and GROUPS to run GLMER
for (ROI in ROIs) {
  for (GROUP in GROUPS) {
    
    # define the formula
    my_formula = as.formula(paste0(ROI, ' ~ MRI_days_ses2 + age + mean_fd + good_run + (1 | sub)'))
    
    # use try to skip instances where there are convergence failures
    result = try({
      
      # fit the model
      model = glmer(formula = my_formula, data = filter(all_data, study_group == GROUP), family = binomial)
      
      # compile results
      stat_summary = summary(model)
      
      # save results
      if (save_tables) {
        write.table(stat_summary$coefficients,glue('{tbl_dir}tbl_s8_{ROI}_{GROUP}.txt'), 
                    row.names = TRUE, sep = "\t")
      }
      
      # print results
      if (print_tables){
        print(ROI)
        print(GROUP)
        print(stat_summary)
      }
    
    }, silent = TRUE) # suppress error messages

    if (inherits(result, "try-error")) {
      cat("Error occurred for ROI:", ROI, "and GROUP:", GROUP, "\n")

    }
  }
}
```

Table S15
```{r}
# load data
all_data = read_csv(glue('{data_dir}tbl_s15.csv'), show_col_types = FALSE)

# define variables 
ROIs = c('VWFA1','VWFA2','FFA1','FFA2')
assessments=c('wj_brs','wj_rf','twre_index','wj_mff_ss')

# loop through ROis and GROUPS to run GLMER
for (ROI in ROIs) {
  for (assessment in assessments) {
    
    # define the formula
    my_formula = as.formula(paste0(ROI,' ~ ',assessment,'_trait + ',assessment,'_state * study_group + age +mean_fd + good_run + (1 | sub)'))
    
    # use try to skip instances where there are convergence failures
    result = try({
      
      # fit the model
      model = glmer(formula = my_formula, data = all_data, family = binomial)
      
      # compile results
      stat_summary = summary(model)
      
      # save results
      if (save_tables) {
        write.table(stat_summary$coefficients,glue('{tbl_dir}tbl_s15_{ROI}_{assessment}.txt'), 
                    row.names = TRUE, sep = "\t")
      }
      
      # print results
      if (print_tables){
        print(ROI)
        print(assessment)
        print(stat_summary)
      }

    
    }, silent = TRUE) # suppress error messages

    if (inherits(result, "try-error")) {
      cat("Error occurred for ROI:", ROI, "and assessment:", assessment, "\n")

    }
  }
}
```
